server {
    listen 80;
    root /var/www/html;
    
    error_page 403 /bloqueio.html;
    
    location = /bloqueio.html {
        root /usr/share/nginx/html;
    }

    location / {
        proxy_pass http://python_waf:5000;
        proxy_set_header X-Original-URI $request_uri;
        proxy_set_header X-Original-Method $request_method;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location ^~ /_php_backend {
        internal;
        rewrite ^/_php_backend(.*)$ $1 break;
        
        fastcgi_pass php_app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root/index.php;
    }
}
